version: "1.0"
services:
  worker:
    build: .
    environment:
    
    INFOPIC: $INFOPIC
    EVENT_LOGS: $EVENT_LOGS
    BOT_USERNAME: $BOT_USERNAME
    BOT_NAME: $BOT_NAME
    CERT_PATH: $CERT_PATH
    API_ID: $API_ID
    API_HASH: $API_HASH
    BOT_ID: $BOT_ID
    DB_URI: $DATABASE_URL
    MONGO_DB_URI: $MONGO_DB_URI
    DONATION_LINK: $DONATION_LINK
    VIRUS_API_KEY: $VIRUS_API_KEY
    ALLOW_EXCL: $ALLOW_EXCL
    CASH_API_KEY: $CASH_API_KEY
    TIME_API_KEY: $TIME_API_KEY
    AI_API_KEY: $AI_API_KEY
    WALL_API: $WALL_API
    SUPPORT_CHAT: $SUPPORT_CHAT
    SPAMWATCH_SUPPORT_CHAT: $SPAMWATCH_SUPPORT_CHAT
    SPAMWATCH_API: $SPAMWATCH_API
    ARQ_API_KEY: $ARQ_API_KEY
    ALLOW_CHATS: $ALLOW_CHATS
    TOKEN: $TOKEN
    OWNER_ID: $OWNER_ID
    JOIN_LOGGER: $JOIN_LOGGER
    OWNER_USERNAME: $OWNER_USERNAME
    DRAGONS: $DRAGONS
    DEV_USERS: $DEV_USERS
    DEMONS: $DEMONS
    WOLVES: $WOLVES
    TIGERS: $TIGERS
    BL_CHATS: $BL_CHATS
